### ISSUE TITLE
Why are the UsesLibrary tags missing?

### ISSUE THREAD

**Issue by Cybrosys** [datalogic/xamarin-samples#1]
A quick question, why don't you have the following tags in your AssemblyInfo.cs files?

`[assembly: UsesLibrary(Name = "com.datalogic.extension.selfshopping")]`
`[assembly: UsesLibrary(Name = "com.datalogic.device")]`

**Comment by codybrookshear** [comment]
Hi Mikael. 

It happens for you behind the scenes; those tags get set in AssemblyInfo.cs in the NuGet packages directly (datalogic-xamarin-sdk and datalogic-xamarin-sdk-selfshopping), so it's not necessary to do so in your application.

-Cody

**Comment by Cybrosys** [comment]
OK. I was worried that was the case. I'm using compiler flags depending on which hardware i'm compiling for, so I need to be able to include/exclude certain UsesLibrary statements otherwise I can't deploy.

For example:
```
#if DATALOGIC
[assembly: UsesLibrary(Name = "com.datalogic.extension.selfshopping")]
[assembly: UsesLibrary(Name = "com.datalogic.device")]
#elif
...
...
#endif
```

I'll continue using my own Bindings Libraries then 😄

**Comment by codybrookshear** [comment]
Hi Mikael,
I have made the requested change regarding having the UsesLibrary embedded in the NuGet packages. Please update to these NuGet packages:

Datalogic Xamarin SDK 1.4.78-beta
Datalogic Xamarin SDK Self-Shopping 1.1.8-beta

You will need to include a uses-library statement to either AndroidManifest.xml or AssemblyInfo.cs in your application now.  See here for more details:
https://datalogic.github.io/xamarin/quick-start/#Android manifest

Also, the sample projects have been updated to use the new libraries and have the necessary changes in AssemblyInfo.cs:
https://github.com/datalogic/xamarin-samples

Thanks,
Cody Brookshear

**Comment by Cybrosys** [comment]
Hi,

I think there was a miscommunication here.

The issue is that you have the UseLibraryAttribute tags embedded in your NuGet packages. This makes it impossible for me to use them because I have the same project for multiple different hardware vendors, but different build configurations.

When I add your NuGet packages to the project, I'm no longer able to install my app on any other hardware, because the installation tries to validate that the specified libraries exist on the non-datalogic-device.

Please remove any UseLibraryAttribute from your NuGet packages so we can manage it ourselves.

```
#if VENDOR_X
[assembly: UsesLibrary(Name = "....")]

[assembly: UsesPermission(Name = "....")]
[assembly: UsesLibrary(Name = "....")]
#elif DATALOGIC
[assembly: UsesLibrary(Name = "com.datalogic.extension.selfshopping")] // Cradle
[assembly: UsesLibrary(Name = "com.datalogic.device")] // Scanning
#elif VENDOR_Y
....
#endif
```

**Comment by codybrookshear** [comment]
Mikael,
Is this still an issue for you? I can't find this issue in the xamarin-samples repo any longer...

Cody
________________________________

**Comment by Cybrosys** [comment]
@codybrookshear No, I was at fault. I thought I was looking at the source code of the NuGet package when I was looking at the source code of a Sample app; that's why I removed my previous comment.

We have successfully swapped out our old binding libraries for your NuGet packages and everything is up and running. Thank you.
