### ISSUE TITLE
App restarts on device Cradle

### ISSUE THREAD

**Issue by tushar9919** [datalogic/xamarin-samples#2]
Hi

I have developed scanner application and i am using DL Axists but when i connect the device for charging or disconnect from charging my app gets restarted and then the app crashes. So can i stop restarting my app on charging or is there any other solution for this. 
Please let me know as i struct very badly.

Thanks.

**Comment by guidodavide** [comment]
Hi Tushar,

I'm not an expert Xamarin developer,
but I can tell you that on Android whenever you put your device on the cradle a specific event is triggered. Typically Android notifies your activity of an important "UI" change, that can be managed or not.

Please follow the following links:
https://stackoverflow.com/questions/7618703/activity-lifecycle-oncreate-called-on-every-re-orientation
https://developer.android.com/guide/topics/manifest/activity-element.html (see **android:configChanges**)

> What happen when orientation changed
> Life Cycle of orientation
> 
> onPause();
> onSaveInstanceState();
> onStop();
> onDestroy();
> 
> onCreate();
> onStart();
> onResume();
> ---- app recreated and now is running ---
> 
> **If you do long operation in onCreate() and want prevent re-create your activity add configChanges  attribute in your mainfest**
```
<activity android:name=".MyActivity"
          android:configChanges="orientation|keyboardHidden|screenSize"
          android:label="@string/app_name">
```
My advice is to manage correctly inside the **android:configChanges** the Android events:
orientation, screenSize, uiMode (as per linked doc).

Hope it helps, I'm not sure if in Xamarin you edit the standard AndroidManifest like in native apps.

Guido

**Comment by tushar9919** [comment]
Hi Guido,

Thank you very much. 

Your hint has worked for me. I will post the solution below so it can help someone who is facing this problem.

For native users, add this

```
<activity android:name=".MyActivity"
          android:configChanges="uiMode"
          android:label="@string/app_name">
```

For Xamarin forms Users, add below line on the main activity as attribute.
`[Activity(ConfigurationChanges =  ConfigChanges.UiMode)]`



Tushar
