### ISSUE TITLE
Target Framework Issue

### ISSUE THREAD

**Issue by tanieee28** [datalogic/xamarin-samples#3]
Hey,
I am unaware about the way u have implemented the things, and i am also a beginner in this.

Let me explain u my problem, i am looking for an sdk that can read the barcode clicked by barcode reader and get that in my c# code using some api provided by barcode reader. (I dont even have any assurance that, is there any barcode reader with ethernet capabilities so that i can call its api.)

When i saw your Samples, in package.config the target framework mentioned is monoandroid so, can i change it, with my framework requirement. It might be a stupid question, please help me in this.

Thanks in Advance. :)

**Comment by codybrookshear** [comment]
Hi,
Are you using a Datalogic brand Android device?  This library requires the built-in scanner hardware included in Datalogic devices.

Thanks!
Cody
