### ISSUE TITLE
Is it working with Xamarin.forms

### ISSUE THREAD

**Issue by valentinmagrez** [datalogic/xamarin-samples#4]
In the sample you are using it with Xamarin native but I am trying to use it with Xamarin.forms without any success. I opened a question on [stackoverflow](https://stackoverflow.com/questions/52845063/data-logic-sdk-integration-throws-java-lang-noclassdeffounderror).

Do you have any idea why?

**Comment by valentinmagrez** [comment]
I just forget to add this line in android manifest: `<uses-library android:name="com.datalogic.device" android:required="true" />`

**Comment by codybrookshear** [comment]
Great! Glad you figured it out :)

**Comment by maeseelek** [comment]
Do you have any example with xamarin.forms and datalogic SDK?

**Comment by codybrookshear** [comment]
@maeseelek take a look at this 3rd party Xamarin.Forms example:
https://github.com/datalogic/xamarin-samples#xamarinformsdatalogicsdkexample
