### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by EuroEager2008** [datalogic/xamarin-samples#5]
DeviceSampleAPI cannot be deployed to emulator (and I guess the same applies to a real Android HW).
I am using VS2017 15.9.7 and the following message is shown in the error list:

ADB0010: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/DeviceSampleAPI.DeviceSampleAPI-__W2zgnsfNPT5DVAC-3LcA==: Package DeviceSampleAPI.DeviceSampleAPI requires unavailable shared library com.datalogic.device; failing!]
   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\579\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 341
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\579\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 753
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()		 	0

**Comment by codybrookshear** [comment]
> DeviceSampleAPI.DeviceSampleAPI requires unavailable shared library com.datalogic.device

This package is only available on real Datalogic devices that have scanner hardware. This Xamarin library is not designed for camera-based scanning.

**Comment by EuroEager2008** [comment]
I think I never said I want to use camera for scanning, I have a device actually, a RIDA DBT6400
Serial number available, but not until tomorrow

Med vennlig hilsen
Magne Ryholt
Tel: +47 92 61 89 33

**Comment by codybrookshear** [comment]
Magne,

Ah, I see, you are using the RIDA. Sorry I made the assumption that you wanted to use the camera for scanning. Unfortunately, we don't have a Xamarin library for the RIDA. This Xamarin library i's only for devices with built-in scanners (DL-Axist, Skorpio X4 Android, Falcon X4 Android, Joya Touch A6, Memor 1, Memor 10).

That said, I realize this doesn't help much if you were hoping for a Xamarin library, but I will point you to our Android (Java) library for the RIDA just in case you haven't seen it yet:

* A [sample app](https://github.com/datalogic/hhs-android-core-sdk-demoapp) that includes the SDK as an AAR directly

* The [javadoc](https://datalogic.github.io/hhs-android-core-sdk-docs/) documentation for the SDK

Cody

**Comment by EuroEager2008** [comment]
Thanks, I will have a look at those javalibs.
All I want is to use BT SPP profile so I guess there should be some standard things for that even in the Xamarin world

Vennlig hilsen
Magne Ryholt
Mob: +47 92 61 89 33
________________________________
