### ISSUE TITLE
Access Datalogic namespace from the .Net standard library

### ISSUE THREAD

**Issue by Lazys** [datalogic/xamarin-samples#6]
Hi, I've got Xamarin forms project with following projects structure:
- MobileApp.App (.Net Standard project)
- MobileApp.App.Android (Xamarin Android project)

I reference MobileApp.App project from the MobileApp.App.Android project.

When I install your package (datalogic-xamarin-sdk) into MobileApp.App.Android project everything works fine, but when I'm trying to install package to the MobileApp.App project I cannot access Datalogic namespace in this project. Only in the MobileApp.App.Android project.

Is there any way to install your library only to the MobileApp.App project and use it there?

**Comment by codybrookshear** [comment]
I don't have a lot of experience with this Xamarin Forms, but I suspect that Xamarin is trying to prevent you from using a platform-specific library (in this case the Android-only Datalogic Xamarin SDK) in a platform-independent context (your MobileApp.App project).
