### ISSUE TITLE
Is this SDK compatible with VS2019 and Xamarin Forms

### ISSUE THREAD

**Issue by jadinning** [datalogic/xamarin-samples#7]
I am having trouble importing the NuGet library into my Xamarin Forms app in VS 2019.
Should I be able to do this?

I am trying to build an app for the Joya Touch A6.

Using Visual Studio 2019, I created a blank Xamarin Forms app.
Minimum Android Version 5.0
Target Android Version 9.0

(I know the Joya has 7.1 but if I set the target to 7.1 I get different issues).

I installed NuGet package datalogic-xamarin-sdk V1.5.88 into the project.

When installing I get a lot of errors like this:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Skipping BLAndroidApp.Droid.Resource.Drawable.avd_hide_password_1. Please check that your Nuget Package versions are compatible.	BLAndroidApp.Android			

datalogic-xamarin-sdk appears in the references but there is no 'Packages' folder containing the dll etc.

When using Com.Datalogic.Device.Info, it cannot be found.

I am a long term Datalogic developer but new to Android Forms and VS 2019 so any help would be very welcome.

John Dinning

**Comment by jadinning** [comment]
Apologies .. this is not an issue with the samples, but with the datalogic-xamarin-sdk and Xamarin Forms.

**Comment by codybrookshear** [comment]
@jadinning I would suggest taking a look at this 3rd party sample project to see how they were able to achieve such a project. I haven't personally done a Xamarin Forms specific project.

## [XamarinFormsDatalogicSDKExample](https://github.com/ahmetkocadogan/XamarinFormsDatalogicSDKExample)
Xamarin.Forms project that uses the Datalogic Xamarin SDK. External sample provided by [ahmetkocadogan](https://github.com/ahmetkocadogan).
