### ISSUE TITLE
Xamarin.Forms Sample Project

### ISSUE THREAD

**Issue by ahmetkocadogan** [datalogic/xamarin-samples#8]
https://github.com/ahmetkocadogan/XamarinFormsDatalogicSDKExample

This is my sample project, based on VS2019 MasterDetail sample Xamarin.Forms project. 

I don't know how to share it for people who are looking for sample Xamarin.Forms project that uses Datalogic Xamarin SDK, so i post it here.

**Comment by codybrookshear** [comment]
Nice! I added a link to it in the [README](https://github.com/datalogic/xamarin-samples/blob/master/README.md). Thanks.
